2025-03-11 18:34:52,527 [INFO] USER:kumari_sakshi generate.py:72:project LOG: Project name: task03
2025-03-11 18:34:52,527 [INFO] USER:kumari_sakshi generate.py:79:project LOG: Project path: C:\Users\kumari_sakshi\Desktop\AWS
2025-03-11 18:34:52,553 [INFO] USER:kumari_sakshi project.py:77:generate_project_structure LOG: Project task03 folder has been successfully created.
2025-03-11 18:34:52,553 [INFO] USER:kumari_sakshi helper.py:330:timed LOG: Stage project, elapsed time: 0:00:00.026116
2025-03-11 18:49:03,592 [INFO] USER:kumari_sakshi handlers.py:106:syndicate LOG: Configuration used: C:\Users\kumari_sakshi\Desktop\AWS\AWS\task01\.syndicate-config-dev
2025-03-11 18:49:03,605 [ERROR] USER:kumari_sakshi decorators.py:136:wrapper LOG: sdct.conf does not exist inside C:\Users\kumari_sakshi\Desktop\AWS\AWS\task01\.syndicate-config-dev folder
2025-03-11 18:49:03,612 [ERROR] USER:kumari_sakshi decorators.py:137:wrapper LOG: Traceback (most recent call last):
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\handlers.py", line 107, in syndicate
    initialize_connection()
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\__init__.py", line 106, in initialize_connection
    CONFIG = ConfigHolder(CONF_PATH)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\conf\processor.py", line 63, in __init__
    self._init_conf_config(dir_path=dir_path)
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\conf\processor.py", line 92, in _init_conf_config
    raise AssertionError(
AssertionError: sdct.conf does not exist inside C:\Users\kumari_sakshi\Desktop\AWS\AWS\task01\.syndicate-config-dev folder
Traceback (most recent call last):
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\handlers.py", line 107, in syndicate
    initialize_connection()
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\__init__.py", line 106, in initialize_connection
    CONFIG = ConfigHolder(CONF_PATH)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\conf\processor.py", line 63, in __init__
    self._init_conf_config(dir_path=dir_path)
  File "C:\Users\kumari_sakshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\syndicate\core\conf\processor.py", line 92, in _init_conf_config
    raise AssertionError(
AssertionError: sdct.conf does not exist inside C:\Users\kumari_sakshi\Desktop\AWS\AWS\task01\.syndicate-config-dev folder
2025-03-11 18:53:01,392 [INFO] USER:kumari_sakshi s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-6675'
2025-03-11 18:53:01,392 [INFO] USER:kumari_sakshi s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-6675'
2025-03-11 18:53:01,392 [INFO] USER:kumari_sakshi helper.py:525:convert LOG: Stripping run_id:JAP-11,run_type:stm,type:user,user_id:39153c03 from "," a bit..
2025-03-11 18:53:01,392 [INFO] USER:kumari_sakshi helper.py:529:convert LOG: Converting: run_id:JAP-11,run_type:stm,type:user,user_id:39153c03 to dict..
2025-03-11 18:53:01,392 [INFO] USER:kumari_sakshi helper.py:541:convert LOG: Converted to such a dict: {'run_id': 'JAP-11', 'run_type': 'stm', 'type': 'user', 'user_id': '39153c03'}
2025-03-11 18:53:04,138 [WARNING] USER:kumari_sakshi generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2025-03-11 18:53:04,147 [WARNING] USER:kumari_sakshi generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\kumari_sakshi\Desktop\AWS\task03\.syndicate-config-dev
2025-03-11 18:53:04,154 [INFO] USER:kumari_sakshi generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\kumari_sakshi\Desktop\AWS\task03\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\kumari_sakshi\Desktop\AWS\task03\.syndicate-config-dev
2025-03-11 18:53:04,161 [INFO] USER:kumari_sakshi helper.py:330:timed LOG: Stage config, elapsed time: 0:00:02.769493
